services:
    palm-dev-env:
        image: palm-dev-env
        container_name: palm-dev-env
        hostname: palm
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./sources/
              target: /home/devel/sources
            - type: bind
              source: ./sdcard/
              target: /home/devel/sdcard
            - type: bind
              source: ./j2mewtk/
              target: /home/devel/j2mewtk
            - type: bind
              source: ./sdcard.bin
              target: /home/devel/sdcard.bin
            - type: bind
              source: ./jar2prc
              target: /home/devel/jar2prc
            - type: bind
              source: ./workspace
              target: /home/devel/workspace
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=${DISPLAY}
